# Generated by Django 4.2.2 on 2023-06-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0005_remove_contact_date_created_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Order',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.IntegerField(default=1)),
        #         ('ordered', models.BooleanField(default=False)),
        #         ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.products')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Cart',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('ordered', models.BooleanField(default=False)),
        #         ('ordered_date', models.DateTimeField(blank=True, null=True)),
        #         ('orders', models.ManyToManyField(to='ecommerce.order')),
        #         ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
 migrations.CreateModel(
    name='Order',
    fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('quantity', models.IntegerField(default=1)),
        ('ordered', models.BooleanField(default=False)),
        ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Products')),
        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
    ],
),
 migrations.CreateModel(
    name='Cart',
    fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('ordered', models.BooleanField(default=True)),
        ('ordered_date', models.DateTimeField(auto_now_add=True)),
        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ('orders', models.ManyToManyField(to='ecommerce.Order')),
    ],
)
    ]