# Generated by Django 4.2.2 on 2023-07-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_cartitem_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
